spring.application.name=cosmocatsmarketplace
application.feature.toggles.cosmoCats=false
application.feature.toggles.kittyProducts=false

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.datasource.url=jdbc:postgresql://localhost:5432/web_cosmocats
spring.datasource.username=postgres
spring.datasource.password=Andriy
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:liquibase/changelog.yaml
spring.liquibase.enabled=true

